### ISSUE TITLE
Getting this error on installing Erlang on RHEL8

### ISSUE THREAD

**Issue by nitinsinghit** [rockandska/ansible-role-erlang#6]
TASK [rockandska.erlang : Install Erlang [RHEL/CentOS]] *****************************
fatal: [172.26.126.248]: FAILED! => changed=false 
  msg: 'Failed to download metadata for repo ''rabbitmq_erlang'': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried'
  rc: 1
  results: []

**Comment by rockandska** [comment]
Did you use master branch or the lastest release ?
I did not publish yet a new release who use cloudsmith repository

NB: did not upgrade rabbitmq role yet to use cloudsmith too

**Comment by nitinsinghit** [comment]
master branch. I ran - ansible-galaxy install rockandska.erlang for the erlang role.

**Comment by rockandska** [comment]
ansible-galaxy doesn't install master branch by default, but the last tag.
Just tried the last version (not already tagged) and works with RHEL 8

If you want to use the last version of the role, see the [ansible-galaxy doc](https://galaxy.ansible.com/docs/using/installing.html#role-versions)

**Comment by nitinsinghit** [comment]
I am very new with ansible. is thise version you talking about ? 0.1.0 ?

**Comment by rockandska** [comment]
> I am very new with ansible. is thise version you talking about ? 0.1.0 ?

I was talking about the master branch who is not already tagged

Use this command to install the last commit from this role :
```
ansible-galaxy install git+https://github.com/rockandska/ansible-role-erlang.git
```

**Comment by nitinsinghit** [comment]
> > I am very new with ansible. is thise version you talking about ? 0.1.0 ?
> 
> I was talking about the master branch who is not already tagged
> 
> Use this command to install the last commit from this role :
> 
> ```
> ansible-galaxy install git+https://github.com/rockandska/ansible-role-erlang.git
> ```

Thanks. it works
